spring:
  application:
    name: spring boot crud-users-api
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  h2:
    console.enabled: true
  jpa:
    defer-datasource-initialization: true

server:
  port: 8080
  servlet:
    context-path: /crud-users-api